openbot_v1:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  arm1_arm2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm1_arm2_joint
    pid: {p: 450.0, i: 100.0, d: 0.8}
  arm2_arm3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm2_arm3_joint
    pid: {p: 300, i: 100.0, d: 0.01}
  arm3_arm4_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm3_arm4_joint
    pid: {p: 50.0, i: 1, d: 0.06}
  arm4_clamp1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm4_clamp1_joint
    pid: {p: 500, i: 500, d: 0.9}
  clamp1_clamp2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: clamp1_clamp2_joint
    pid: {p: 70.0, i: 1.0, d: 0.01}
  base_arm1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_arm1_joint
    pid: {p: 50.0, i: 1.0, d: 0.5}
